package com.example.edpprojekt2.credentials;

public enum Status {
    OK, INVALID_PASSWORD, INVALID_USERNAME, USED_EMAIL_OR_USERNAME, PASSWORDS_DOES_NOT_MATCH,
    USER_NOT_FOUND, INCORRECT_PASSWORD, INCORRECT_EMAIL, EMAIL_DOES_NOT_EXIST
}
